### PR TITLE
Official Docker image

### PR DESCRIPTION
**Pull request by dmcallejo**
Hello!
I've written a little multistage Dockerfile to potentially provide an official docker image for xTeVe.
Docker will take care of building the application in the first stage and distribute it in a lightweight Alpine image in the final one.
This should be paired with an automated build in Dockerhub set to build tags and maybe master so it would run seamlessly.

If the pull request gets approved, I'll also write the documentation, usage and quick start of the image.

Cheers!

### CODE REVIEW

**Comment by MCTyler** [comment]
This has already been done and is on our Discord support page. Please provide more information as to why yours would be superior.

**Comment by mar-mei** [comment]
The recommended Docker images can be found on the readme page. https://github.com/xteve-project/xTeVe/blob/master/README.md#recommended-docker-image-linux-64-bit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmcallejo** [comment]
Hello!
I've checked those images in advance and the reasons why I did mine are the following:
 - xTeVe and any other application should be shipped as barebones as possible. This makes the simplest and lightest possible setup and if some user needs any other application to support its personal scenario (crond, zap2xml, guidetogo etc...) imho should use the docker way (as in one app per container) or use the recommended images in the readme. Or maybe even the project could provide them in and official way but in different tags and based in the barebones image.
 - Recommended images are based on binaries rather than be embedded in the source code. By making the multistage dockerfile and setting up the automated build in dockerhub every revision of xTeVe will be automatically published with no effort from the maintainer. Although this should be supported by a Makefile rather than hardcoding the building process in the Dockerfile.

Anyway, I was using for a long time crobibero image which is as well a barebones xTeVe but it hasn't been updated in a year so I made my own, again using the binaries, and after taking a look at the repo thought maybe this would be a good idea, but is up to you whether it is or not :)

Cheers!

**Comment by mar-mei** [comment]
All xTeVe Docker images always link to the same binary. The filename of the binary does not change, so Docker Hub always gets the latest version. Alturismo has an image only with xTeVe without unnecessary additional programs.
We have experienced that many people have problems with external files such as Mount EPG files in the image. That's why the Docker versions were created with the additional tools.

I will not merge your pull request. With changes I could not maintain it, because I have no idea about Docker. In a few days there will be an update, then the Docker Image need VLC and FFmpeg.

Cheers

**Pull request closed without merging**
