### PR TITLE
Support relaying multicast stream through UDPXy

### PR DESCRIPTION
**Pull request by 5Ub-Z3r0**
This patch adds support for relaying multicast streams through a popular stream relay, UDPxy (http://www.udpxy.com/).

It adds a new configuration settings (`udpxy`) in `settings.json`. If that is set to point to a UDPxy server , and the stream is multicast, then the stream URL is rewritten to be accessed through UDPxy.

Since I find it hard to figure out how to edit and rebuild the static file cache in webUI.go, I've ported it to use esc (http://github.com/mjibson/esc) instead, as IMO It makes it a little easier to update after changing assets.

### CODE REVIEW

**Comment by mar-mei** [comment]
> Since I find it hard to figure out how to edit and rebuild the static file cache in webUI.go, I've ported it to use esc ([http://github.com/mjibson/esc](https://github.com/mjibson/esc)) instead, as IMO It makes it a little easier to update after changing assets.

Can this be easily undone?
```
xteve.go Line 51: Dev = true
```
Use the local static files and build the src/webUI.go file with every go run.
```
go run xteve.go
```

Do you also have a UDP stream to test?

**Comment by 5Ub-Z3r0** [comment]
> Can this be easily undone?



> > Since I find it hard to figure out how to edit and rebuild the static file cache in webUI.go, I've ported it to use esc ([http://github.com/mjibson/esc](https://github.com/mjibson/esc)) instead, as IMO It makes it a little easier to update after changing assets.
> 
> Can this be easily undone?

Yes, I can remove the commit from this pull request I think (or open another). 

> ```
> xteve.go Line 51: Dev = true
> ```
> 
> Use the local static files and build the src/webUI.go file with every go run.
> 
> ```
> go run xteve.go
> ```
> 
> Do you also have a UDP stream to test?

I have a few from my internet provider, which works. Don't have any that you can access outside their network to test, though.

**Comment by mar-mei** [comment]
Do the UDP streams work even if the buffer is activated in the settings (xTeVe, FFmpeg, VLC)?

I will also add a CLI flag for the developer mode. This is more obvious than the variable in the code.

**Comment by mar-mei** [comment]
Flag is now available:
```
go run xteve.go -dev
```

**Comment by 5Ub-Z3r0** [comment]
Ok so apparently I can't modify the tracked branch for this, so I'll close this PR and open another.

**Pull request closed without merging**
