### PR TITLE
Don't use Hash if Paramters are all Empty

### PR DESCRIPTION
**Pull request by Asdoos**
Fix for Issue #237

### CODE REVIEW

**Comment by xteve-project** [comment]
Does the problem also exist with the current beta? A few weeks ago there was another problem #230, the solution was to change the channel name in the hash function.
The change is only in beta so far.

**Comment by Asdoos** [comment]
Where can I find the Beta branch?
I can only checkout the master

**Comment by xteve-project** [comment]
You can update xTeVe to the beta by using the command line:
https://github.com/xteve-project/xTeVe#xteve-beta-branch

or download the beta binary:
https://github.com/xteve-project/xTeVe-Downloads/tree/beta

**Comment by Asdoos** [comment]
Oke yes- seems 2 be fixed in Beta

**Comment by ilikenwf** [comment]
FYI, forcing the use of the full scan in my case fixes poorly built lists that come from dubious sources...and I'm cheap.

**Pull request closed without merging**
