### PR TITLE
Feature: Replace PPV channels title/desc with filtered channel name

### PR DESCRIPTION
**Pull request by Fyb3roptik**
## Issue
* Some IPTV providers list the live PPV events in the channel name instead of the title or desc, leaving the guide to say "No events today".
* When using Plex, channel name is not a used field, so therefore rendering no information in the guide

## Solution
* Add the ability to let xTeVe take the channel name, filter it to remove any PPV channel name and number, then paste in the filtered event name into the Title and Desc fields.

Here are before and after screenshots so you can see the example issue and solution.

```xml
<channel id="1100">
<display-name>PPV-2: Navarrete vs. Gonzalez (10.15 8:30PM ET/5:30PM PT)</display-name>
<icon src=""/>
</channel>
<programme channel="1100" start="20211015090000 -0400" stop="20211016000000 -0400">
<title lang="">No event today on this channel</title>
<desc lang="">No event today on this channel</desc>
<icon height="" src="" width=""/>
<credits/>
<video/>
<date/>
</programme>
```
plex image link before

```xml
<channel id="1100">
<display-name>PPV-2: Navarrete vs. Gonzalez (10.15 8:30PM ET/5:30PM PT)</display-name>
<icon src=""/>
</channel>
<programme channel="1100" start="20211015090000 -0400" stop="20211016000000 -0400">
<title lang="">Navarrete vs. Gonzalez (10.15 8:30PM ET/5:30PM PT)</title>
<desc lang="">Navarrete vs. Gonzalez (10.15 8:30PM ET/5:30PM PT)</desc>
<icon height="" src="" width=""/>
<credits/>
<video/>
<date/>
</programme>
```
plex image link after
xTeVe settings page

### CODE REVIEW

**Comment by Fyb3roptik** [comment]
and oh no I think running go mod vendor probably added a ton of files here...

**Comment by ReenigneArcher** [comment]
I am not a developer of xteve and this is my opinion only, but this doesn't seem like an xteve issue. Xteve should work with epg files that use the correct standard (https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd).

Instead of putting this into xteve, you should probably just create a script that fixes your epg file.

**Comment by Fyb3roptik** [comment]
While that is all well and good and I agree with you mostly, unfortunately its not something possible without patching xteve. I have a fork and am happy just pulling changes into it and using that for myself, but figured I wasnt the only one having to deal with an iptv company doing weird things. This is also why I made the option to turn it off (it is disabled by default)

**Comment by Fyb3roptik** [comment]
Closing this PR since it appears no one is here doing any checking. I have a forked repo for anyone interested.

https://github.com/Fyb3roptik/PlexTeVe

**Pull request closed without merging**
