### PR TITLE
Use relative path when posting HTML forms

### PR DESCRIPTION
**Pull request by ThomasDalla**
For making the website work when using a proxy service to redirect for example http://localhost:8080/xteve to http://172.16.0.2:34400/ (for example when running xteve in a docker container and willing to expose the web service via nginx proxy).

Without using relative path, when we open http://localhost:8080/xteve/web and post our username/password, we are redirected to http://localhost/web (wrong port, wrong path), which doesn't work.

This simple fix makes the website work properly when using redirection proxies as well.

### CODE REVIEW

**Comment by mar-mei** [comment]
With your change, this URL is called:
http://192.168.178.90:34400/web/web/

Not Found [404]

If you test that, change line 51 in the xteve.go file to: 

> const Dev = true

Then the local HTML files are used

**Comment by ThomasDalla** [comment]
Thanks for tip. I indeed had to simply use ./ to make it work.

**Comment by mar-mei** [comment]
Can you test if that would work too?
`<form id="authentication" action="" method="post">`

**Comment by ThomasDalla** [comment]
Yes, it becomes `<form id="authentication" action="" method="post" _lpchecked="1">` in the generated HTML and works as well. Is that preferred?

**Comment by ThomasDalla** [comment]
Can it be merged?

**Comment by mar-mei** [comment]
Yes, your changes will be in beta in the next few days. Then others can also test it.

**Pull request merged**
