### PR TITLE
Add support for proxying multicast streams through a UDPxy server.

### PR DESCRIPTION
**Pull request by 5Ub-Z3r0**
This patch adds support for relaying multicast streams through a popular stream relay, UDPxy (http://www.udpxy.com/).

It adds a new configuration settings (`udpxy`) in `settings.json`. If that is set to point to a UDPxy server , and the stream is multicast, then the stream URL is rewritten to be accessed through UDPxy.

This is similar to https://github.com/xteve-project/xTeVe/pull/132, without the change to the asset pipeline as requested. Instead, I've done a run of xteve with the dev flag enabled, to regenerate the cache in `src/webUI.go`.

### CODE REVIEW

**Comment by mar-mei** [comment]
Your pull request is for testing in the beta branch. Can you write a few more lines that I can then include in the documentation?

**Comment by 5Ub-Z3r0** [comment]
Sure. Which format would work? Do you want it in another pull request for https://github.com/xteve-project/xTeVe-Documentation?

**Comment by mar-mei** [comment]
it’s enough if you write it in here. I add it to the documentation myself when everything is in the master.

**Comment by 5Ub-Z3r0** [comment]
Ack.

So, this change allows xTeVe to proxy multicast streams present in a playlist through UDPxy (www.udpxy.com). UDPxy is a data stream relay, capable of listening to multicast UDP stream and provide a tcp unicast stream.

It adds a new configuration options, `UDPxy`, configurable both via the configuraiton UI and via an entryin `settings.json' (the key for this is `udpxy`). This can be set to a `host` (or `host:port`).

When this is set, every **multicast** stream URL present in the playlist (i.e., a stream that begins with `udp://@`) is rewritten to be proxied through the UDPxy server configured, regardless of the buffer settings. For example, if the Stream Buffer settings is set to none, then the rewritten url will be passed to the requested; if set to `ffmpeg`, then ffmpeg will be instructed to access the video stream passing through UDPxy.

**Pull request merged**
